/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bot.client;

import java.net.URI;
import java.net.URISyntaxException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse.BodyHandler;
import java.net.http.HttpResponse.BodyHandlers;

import com.github.kwhat.jnativehook.GlobalScreen;
import com.github.kwhat.jnativehook.NativeHookException;
import com.github.kwhat.jnativehook.keyboard.NativeKeyEvent;
import com.github.kwhat.jnativehook.keyboard.NativeKeyListener;

public class App {

    private static final String SERVER_URL = "http://84.38.185.63:4567/command/";

    private static final HttpClient httpClient = HttpClient.newHttpClient();

    public static void main(String[] args) {
        System.out.println("Hello World! 111");

        try {
            GlobalScreen.registerNativeHook();
            GlobalScreen.addNativeKeyListener(new NativeKeyListener() {

                @Override
                public void nativeKeyTyped(NativeKeyEvent nativeEvent) {
                }

                @Override
                public void nativeKeyReleased(NativeKeyEvent nativeEvent) {
                    String keyText = NativeKeyEvent.getKeyText(nativeEvent.getKeyCode());
                    System.out.println("User typed: " + keyText);

                    switch (keyText) {
                        case "F1":
                        case "F2":
                        case "F3":
                        case "F4":
                        case "F5":
                        case "F6": {
                            sendCommand(keyText);
                            break;
                        }
                    }
                }

                @Override
                public void nativeKeyPressed(NativeKeyEvent nativeEvent) {
                }
            });
        } catch (NativeHookException e) {
            e.printStackTrace();
        }
    }

    private static void sendCommand(String command) {
        try {
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(new URI(SERVER_URL + command))
                    .GET()
                    .build();
            httpClient.send(request, BodyHandlers.ofString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
